#!/usr/bin/env python3
"""Generate LVGL animimg descriptors from the selected Noto cat GIFs."""

from __future__ import annotations

from bisect import bisect_right
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageOps, ImageSequence


TARGET_SIZE = 80
SAMPLE_FRAMES = 8


@dataclass(frozen=True)
class CatAsset:
    key: str
    caption: str
    gif_name: str
    aliases: tuple[str, ...]


ASSETS = (
    CatAsset(
        "noto_smiley_cat_1f63a",
        "smiley cat",
        "noto_smiley_cat_1f63a.gif",
        ("smiley", "1f63a", "idle", "listen", "listening", "relaxed", "llm"),
    ),
    CatAsset(
        "noto_smile_cat_1f638",
        "smile cat",
        "noto_smile_cat_1f638.gif",
        ("smile", "1f638", "happy", "wifi", "link", "connect", "connecting"),
    ),
    CatAsset(
        "noto_joy_cat_1f639",
        "joy cat",
        "noto_joy_cat_1f639.gif",
        ("joy", "1f639", "speak", "speaking", "tts", "excited"),
    ),
    CatAsset(
        "noto_heart_eyes_cat_1f63b",
        "heart eyes cat",
        "noto_heart_eyes_cat_1f63b.gif",
        ("heart", "heart_eyes", "1f63b", "love", "loving"),
    ),
    CatAsset(
        "noto_smirk_cat_1f63c",
        "smirk cat",
        "noto_smirk_cat_1f63c.gif",
        ("smirk", "1f63c", "thinking"),
    ),
    CatAsset(
        "noto_kissing_cat_1f63d",
        "kissing cat",
        "noto_kissing_cat_1f63d.gif",
        ("kiss", "kissing", "1f63d"),
    ),
    CatAsset(
        "noto_pouting_cat_1f63e",
        "pouting cat",
        "noto_pouting_cat_1f63e.gif",
        ("pout", "pouting", "1f63e", "angry", "recover", "recovering"),
    ),
    CatAsset(
        "noto_crying_cat_1f63f",
        "crying cat",
        "noto_crying_cat_1f63f.gif",
        ("cry", "crying", "1f63f", "sad"),
    ),
    CatAsset(
        "noto_scream_cat_1f640",
        "scream cat",
        "noto_scream_cat_1f640.gif",
        ("scream", "1f640", "error", "surprise", "surprised", "afraid", "fear"),
    ),
    CatAsset(
        "noto_cat_face_1f431",
        "cat face",
        "noto_cat_face_1f431.gif",
        ("cat_face", "face", "1f431", "boot", "starting", "unknown"),
    ),
)


def c_name(key: str) -> str:
    return key.replace("-", "_")


def load_frames(path: Path) -> tuple[list[Image.Image], list[int]]:
    with Image.open(path) as image:
        frames = [frame.convert("RGBA") for frame in ImageSequence.Iterator(image)]
        durations = [int(frame.info.get("duration", 0) or 30) for frame in ImageSequence.Iterator(image)]
    return frames, durations


def union_bbox(frames: Iterable[Image.Image]) -> tuple[int, int, int, int]:
    bbox: tuple[int, int, int, int] | None = None
    for frame in frames:
        frame_bbox = frame.getchannel("A").getbbox()
        if frame_bbox is None:
            continue
        if bbox is None:
            bbox = frame_bbox
        else:
            bbox = (
                min(bbox[0], frame_bbox[0]),
                min(bbox[1], frame_bbox[1]),
                max(bbox[2], frame_bbox[2]),
                max(bbox[3], frame_bbox[3]),
            )
    if bbox is None:
        return (0, 0, TARGET_SIZE, TARGET_SIZE)
    return bbox


def fit_frame(frame: Image.Image, bbox: tuple[int, int, int, int]) -> Image.Image:
    cropped = frame.crop(bbox)
    resized = ImageOps.contain(
        cropped,
        (TARGET_SIZE, TARGET_SIZE),
        method=Image.Resampling.LANCZOS,
    )
    canvas = Image.new("RGBA", (TARGET_SIZE, TARGET_SIZE), (0, 0, 0, 0))
    x = (TARGET_SIZE - resized.width) // 2
    y = (TARGET_SIZE - resized.height) // 2
    canvas.alpha_composite(resized, (x, y))
    return canvas


def select_frames(frames: list[Image.Image], durations: list[int]) -> list[int]:
    total = max(1, sum(durations))
    cumulative: list[int] = []
    running = 0
    for duration in durations:
        running += max(1, duration)
        cumulative.append(running)

    indices: list[int] = []
    for i in range(SAMPLE_FRAMES):
        target = (total * i) // SAMPLE_FRAMES
        index = bisect_right(cumulative, target)
        indices.append(min(index, len(frames) - 1))
    return indices


def emit_bytes(data: bytes, indent: str = "    ") -> str:
    lines: list[str] = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append(indent + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(lines)


def emit_header() -> str:
    return f"""/* Auto-generated by generate_noto_cat_lvgl.py. */
#ifndef RIVER_NOTO_CAT_ANIM_H
#define RIVER_NOTO_CAT_ANIM_H

#include <stddef.h>
#include <stdint.h>

#include \"lvgl.h\"

#ifdef __cplusplus
extern \"C\" {{
#endif

#define RIVER_NOTO_CAT_ANIM_WIDTH      {TARGET_SIZE}U
#define RIVER_NOTO_CAT_ANIM_HEIGHT     {TARGET_SIZE}U
#define RIVER_NOTO_CAT_ANIM_FRAME_HINT {SAMPLE_FRAMES}U

typedef struct {{
    const char *key;
    const char *caption;
    const lv_image_dsc_t * const *frames;
    uint16_t frame_count;
    uint32_t duration_ms;
}} river_noto_cat_anim_t;

const river_noto_cat_anim_t *river_noto_cat_anim_default(void);
const river_noto_cat_anim_t *river_noto_cat_anim_resolve(const char *token);
const river_noto_cat_anim_t *river_noto_cat_anim_get(size_t index);
size_t river_noto_cat_anim_count(void);

#ifdef __cplusplus
}}
#endif

#endif /* RIVER_NOTO_CAT_ANIM_H */
"""


def emit_c(raw_dir: Path) -> tuple[str, list[tuple[CatAsset, int, int, tuple[int, int, int, int], list[int]]]]:
    out: list[str] = [
        "/* Auto-generated by generate_noto_cat_lvgl.py. */",
        '#include "river_noto_cat_anim.h"',
        "",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "",
        "#ifndef LV_ATTRIBUTE_IMAGE_RIVER_NOTO_CAT",
        "#define LV_ATTRIBUTE_IMAGE_RIVER_NOTO_CAT",
        "#endif",
        "",
    ]
    metadata: list[tuple[CatAsset, int, int, tuple[int, int, int, int], list[int]]] = []

    for asset in ASSETS:
        frames, durations = load_frames(raw_dir / asset.gif_name)
        bbox = union_bbox(frames)
        indices = select_frames(frames, durations)
        duration_ms = max(1, sum(durations))
        stem = c_name(asset.key)

        metadata.append((asset, len(frames), duration_ms, bbox, indices))
        for output_index, frame_index in enumerate(indices):
            image = fit_frame(frames[frame_index], bbox)
            data = image.tobytes("raw", "BGRA")
            map_name = f"{stem}_frame_{output_index:02d}_map"
            dsc_name = f"{stem}_frame_{output_index:02d}"
            out.extend(
                [
                    "static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST",
                    f"LV_ATTRIBUTE_IMAGE_RIVER_NOTO_CAT uint8_t {map_name}[] = {{",
                    emit_bytes(data),
                    "};",
                    "",
                    f"static const lv_image_dsc_t {dsc_name} = {{",
                    "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
                    "    .header.cf = LV_COLOR_FORMAT_ARGB8888,",
                    "    .header.flags = 0,",
                    f"    .header.w = {TARGET_SIZE},",
                    f"    .header.h = {TARGET_SIZE},",
                    f"    .header.stride = {TARGET_SIZE * 4},",
                    f"    .data_size = sizeof({map_name}),",
                    f"    .data = {map_name},",
                    "};",
                    "",
                ]
            )

        out.append(f"static const lv_image_dsc_t * const {stem}_frames[] = {{")
        for output_index in range(len(indices)):
            out.append(f"    &{stem}_frame_{output_index:02d},")
        out.extend(["};", ""])

    for asset in ASSETS:
        stem = c_name(asset.key)
        out.append(f"static const char * const {stem}_aliases[] = {{")
        for alias in asset.aliases:
            out.append(f'    "{alias}",')
        out.extend(["};", ""])

    out.extend(
        [
            "static const river_noto_cat_anim_t river_noto_cat_anim_table[] = {",
        ]
    )
    for asset, _, duration_ms, _, _ in metadata:
        stem = c_name(asset.key)
        out.extend(
            [
                "    {",
                f'        .key = "{asset.key}",',
                f'        .caption = "{asset.caption}",',
                f"        .frames = {stem}_frames,",
                f"        .frame_count = (uint16_t)(sizeof({stem}_frames) / sizeof({stem}_frames[0])),",
                f"        .duration_ms = {duration_ms}U,",
                "    },",
            ]
        )
    out.extend(["};", ""])

    out.extend(
        [
            "typedef struct {",
            "    const char *key;",
            "    const char * const *aliases;",
            "    size_t alias_count;",
            "} river_noto_cat_aliases_t;",
            "",
            "static const river_noto_cat_aliases_t river_noto_cat_alias_table[] = {",
        ]
    )
    for asset in ASSETS:
        stem = c_name(asset.key)
        out.extend(
            [
                "    {",
                f'        .key = "{asset.key}",',
                f"        .aliases = {stem}_aliases,",
                f"        .alias_count = sizeof({stem}_aliases) / sizeof({stem}_aliases[0]),",
                "    },",
            ]
        )
    out.extend(["};", ""])

    out.extend(
        [
            "static char river_noto_cat_tolower(char ch)",
            "{",
            "    if (ch >= 'A' && ch <= 'Z') {",
            "        return (char)(ch - 'A' + 'a');",
            "    }",
            "    return ch;",
            "}",
            "",
            "static bool river_noto_cat_streq_ci(const char *a, const char *b)",
            "{",
            "    if (a == NULL || b == NULL) {",
            "        return false;",
            "    }",
            "    while (*a != '\\0' && *b != '\\0') {",
            "        if (river_noto_cat_tolower(*a) != river_noto_cat_tolower(*b)) {",
            "            return false;",
            "        }",
            "        ++a;",
            "        ++b;",
            "    }",
            "    return *a == '\\0' && *b == '\\0';",
            "}",
            "",
            "static bool river_noto_cat_contains_ci(const char *text, const char *needle)",
            "{",
            "    const char *start;",
            "",
            "    if (text == NULL || needle == NULL || needle[0] == '\\0') {",
            "        return false;",
            "    }",
            "    for (start = text; *start != '\\0'; ++start) {",
            "        const char *h = start;",
            "        const char *n = needle;",
            "",
            "        while (*h != '\\0' && *n != '\\0' &&",
            "               river_noto_cat_tolower(*h) == river_noto_cat_tolower(*n)) {",
            "            ++h;",
            "            ++n;",
            "        }",
            "        if (*n == '\\0') {",
            "            return true;",
            "        }",
            "    }",
            "    return false;",
            "}",
            "",
            "size_t river_noto_cat_anim_count(void)",
            "{",
            "    return sizeof(river_noto_cat_anim_table) / sizeof(river_noto_cat_anim_table[0]);",
            "}",
            "",
            "const river_noto_cat_anim_t *river_noto_cat_anim_get(size_t index)",
            "{",
            "    if (index >= river_noto_cat_anim_count()) {",
            "        return NULL;",
            "    }",
            "    return &river_noto_cat_anim_table[index];",
            "}",
            "",
            "const river_noto_cat_anim_t *river_noto_cat_anim_default(void)",
            "{",
            "    return &river_noto_cat_anim_table[0];",
            "}",
            "",
            "const river_noto_cat_anim_t *river_noto_cat_anim_resolve(const char *token)",
            "{",
            "    size_t i;",
            "",
            "    if (token == NULL || token[0] == '\\0') {",
            "        return river_noto_cat_anim_default();",
            "    }",
            "    for (i = 0U; i < river_noto_cat_anim_count(); ++i) {",
            "        size_t alias;",
            "",
            "        if (river_noto_cat_streq_ci(token, river_noto_cat_anim_table[i].key)) {",
            "            return &river_noto_cat_anim_table[i];",
            "        }",
            "        for (alias = 0U; alias < river_noto_cat_alias_table[i].alias_count; ++alias) {",
            "            if (river_noto_cat_streq_ci(token, river_noto_cat_alias_table[i].aliases[alias])) {",
            "                return &river_noto_cat_anim_table[i];",
            "            }",
            "        }",
            "    }",
            "    for (i = 0U; i < river_noto_cat_anim_count(); ++i) {",
            "        size_t alias;",
            "",
            "        if (river_noto_cat_contains_ci(token, river_noto_cat_anim_table[i].key)) {",
            "            return &river_noto_cat_anim_table[i];",
            "        }",
            "        for (alias = 0U; alias < river_noto_cat_alias_table[i].alias_count; ++alias) {",
            "            if (river_noto_cat_contains_ci(token, river_noto_cat_alias_table[i].aliases[alias])) {",
            "                return &river_noto_cat_anim_table[i];",
            "            }",
            "        }",
            "    }",
            "    return river_noto_cat_anim_default();",
            "}",
            "",
        ]
    )
    return "\n".join(out), metadata


def emit_readme(metadata: list[tuple[CatAsset, int, int, tuple[int, int, int, int], list[int]]]) -> str:
    lines = [
        "# Noto Cat LVGL Animation Assets",
        "",
        "This folder contains firmware-ready LVGL `lv_animimg` resources generated",
        "from the selected Noto animated cat GIFs in `../emoji_candidates/`.",
        "",
        f"- Target size: `{TARGET_SIZE}x{TARGET_SIZE}`",
        f"- Sampled frames per animation: `{SAMPLE_FRAMES}`",
        "- Pixel format: `LV_COLOR_FORMAT_ARGB8888` using LVGL BGRA byte order",
        "- Runtime object: `lv_animimg`, so no runtime GIF decoder or filesystem is required",
        "",
        "## Generated Animations",
        "",
        "| Key | Caption | Source GIF | Source frames | Source duration | Sampled frame indices |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]
    for asset, frame_count, duration_ms, _, indices in metadata:
        index_text = ", ".join(str(index) for index in indices)
        lines.append(
            f"| `{asset.key}` | {asset.caption} | `{asset.gif_name}` | {frame_count} | {duration_ms}ms | `{index_text}` |"
        )
    lines.extend(
        [
            "",
            "## Regeneration",
            "",
            "```bash",
            "cd /root/ameba-river",
            "python3 components/river_ui/assets/noto_cat_lvgl/generate_noto_cat_lvgl.py",
            "```",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    root = Path(__file__).resolve().parent
    raw_dir = root.parent / "emoji_candidates"
    header = root / "river_noto_cat_anim.h"
    source = root / "river_noto_cat_anim.c"
    readme = root / "README.md"

    c_text, metadata = emit_c(raw_dir)
    header.write_text(emit_header(), encoding="utf-8")
    source.write_text(c_text, encoding="utf-8")
    readme.write_text(emit_readme(metadata), encoding="utf-8")

    total_bytes = TARGET_SIZE * TARGET_SIZE * 4 * SAMPLE_FRAMES * len(ASSETS)
    print(f"generated {len(ASSETS)} animations, {SAMPLE_FRAMES} frames each, {total_bytes} raw bytes")
    print(f"wrote {header}")
    print(f"wrote {source}")
    print(f"wrote {readme}")


if __name__ == "__main__":
    main()
