/* Auto-generated by generate_noto_cat_lvgl.py. */
#ifndef RIVER_NOTO_CAT_ANIM_H
#define RIVER_NOTO_CAT_ANIM_H

#include <stddef.h>
#include <stdint.h>

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define RIVER_NOTO_CAT_ANIM_WIDTH      80U
#define RIVER_NOTO_CAT_ANIM_HEIGHT     80U
#define RIVER_NOTO_CAT_ANIM_FRAME_HINT 8U

typedef struct {
    const char *key;
    const char *caption;
    const lv_image_dsc_t * const *frames;
    uint16_t frame_count;
    uint32_t duration_ms;
} river_noto_cat_anim_t;

const river_noto_cat_anim_t *river_noto_cat_anim_default(void);
const river_noto_cat_anim_t *river_noto_cat_anim_resolve(const char *token);
const river_noto_cat_anim_t *river_noto_cat_anim_get(size_t index);
size_t river_noto_cat_anim_count(void);

#ifdef __cplusplus
}
#endif

#endif /* RIVER_NOTO_CAT_ANIM_H */
