CONFIG_AMEBA_RIVER_EN=y
CONFIG_AUDIO_FWK_MENU=y
CONFIG_AUDIO_PASSTHROUGH_MENU=y
CONFIG_RIVER_ONLINE_CONTROL_EN=y
CONFIG_RIVER_DIAG_CMD_EN=y
CONFIG_RIVER_SPEAKER_TEST_AUTOSTART=y
CONFIG_RIVER_SPEAKER_TEST_DIAG_DEFAULT_ON=y
CONFIG_RIVER_LOCAL_VAD_ONLY=y
CONFIG_RIVER_OFFLINE_ASR_RESERVED=y
