CONFIG_AMEBA_RIVER_EN=y
CONFIG_AUDIO_FWK_MENU=y
CONFIG_AUDIO_PASSTHROUGH_MENU=y
CONFIG_AIVOICE_EN_MENU=y
CONFIG_AFE_RES_2MIC50MM_MENU=y
CONFIG_VAD_V8_60K_MENU=y
CONFIG_KWS_XIAOQIANGXIAOQIANG_NIHAOXIAOQIANG_V5_125K_MENU=y
CONFIG_ASR_CN_V10_1M_MENU=y
CONFIG_RIVER_ONLINE_CONTROL_EN=y
CONFIG_RIVER_DIAG_CMD_EN=y
CONFIG_RIVER_AUDIO_ECHO_AUTOSTART=y
CONFIG_RIVER_AUDIO_ECHO_DIAG_DEFAULT_ON=y
CONFIG_RIVER_VOICE_PREPROC_AIVOICE_AFE=y
CONFIG_RIVER_LOCAL_VAD_ONLY=y
CONFIG_RIVER_OFFLINE_ASR_RESERVED=y
