
sitronix-ts-objs	= sitronix_ts.o sitronix_ts_i2c.o sitronix_ts_spi.o sitronix_ts_utility.o sitronix_ts_mt.o sitronix_ts_nodes.o sitronix_ts_upgrade.o sitronix_ts_test.o sitronix_ts_proximity.o
obj-m += sitronix-ts.o

