/* Orvibo voice client default server access configuration. */
#ifndef AMEBA_RIVER_ORVIBO_CREDENTIALS_H
#define AMEBA_RIVER_ORVIBO_CREDENTIALS_H

#include "platform_autoconf.h"

#ifdef CONFIG_RIVER_ORVIBO_OTA_URL
#define RIVER_ORVIBO_OTA_URL CONFIG_RIVER_ORVIBO_OTA_URL
#else
#define RIVER_ORVIBO_OTA_URL "https://api.tenclass.net/xiaozhi/ota/"
#endif

#ifdef CONFIG_RIVER_ORVIBO_WS_URL
#define RIVER_ORVIBO_WS_URL CONFIG_RIVER_ORVIBO_WS_URL
#else
#define RIVER_ORVIBO_WS_URL "ws://101.33.235.154:8081/xiaozhi/v1/"
#endif

#ifdef CONFIG_RIVER_ORVIBO_WS_TOKEN
#define RIVER_ORVIBO_WS_TOKEN CONFIG_RIVER_ORVIBO_WS_TOKEN
#else
#define RIVER_ORVIBO_WS_TOKEN ""
#endif

#ifdef CONFIG_RIVER_ORVIBO_WS_SUBPROTOCOL
#define RIVER_ORVIBO_WS_SUBPROTOCOL CONFIG_RIVER_ORVIBO_WS_SUBPROTOCOL
#else
#define RIVER_ORVIBO_WS_SUBPROTOCOL "chat"
#endif

#ifdef CONFIG_RIVER_ORVIBO_PROTOCOL_VERSION
#define RIVER_ORVIBO_PROTOCOL_VERSION CONFIG_RIVER_ORVIBO_PROTOCOL_VERSION
#else
#define RIVER_ORVIBO_PROTOCOL_VERSION 3U
#endif

#ifdef CONFIG_RIVER_ORVIBO_SERVER_WAKE_TEXT
#define RIVER_ORVIBO_SERVER_WAKE_TEXT CONFIG_RIVER_ORVIBO_SERVER_WAKE_TEXT
#else
#define RIVER_ORVIBO_SERVER_WAKE_TEXT "你好小智"
#endif

#define RIVER_ORVIBO_ENABLE_MCP          1

#define RIVER_ORVIBO_AUDIO_SAMPLE_RATE        16000U
#define RIVER_ORVIBO_AUDIO_CHANNELS           1U
#define RIVER_ORVIBO_AUDIO_FRAME_DURATION_MS  60U
#define RIVER_ORVIBO_AUDIO_FORMAT             "opus"

#define RIVER_ORVIBO_WS_TX_MAX          2048
#define RIVER_ORVIBO_WS_RX_MAX          8192
#define RIVER_ORVIBO_WS_QUEUE_MAX       32
#define RIVER_ORVIBO_WS_STABLE_BUF_NUM  24

#endif
